# docker-compose.yml
version: "3"
services:
  api:
    container_name: know-sync-api
    build:
      context: .
      dockerfile: ./Dockerfile-golang
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/api

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./Dockerfile-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=know-sync
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data

  pgweb:
    image: donnex/pgweb
    restart: always
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://postgres:secret@postgres/know-sync?sslmode=disable
    links:
      - postgres:postgres
    ports:
      - "9232:8080"
    depends_on:
      - postgres

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    volumes:
      - ./redis_volume:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  postgres_volume:
  redis_volume:
