FROM golang:1.17

WORKDIR /api

COPY api/go.mod .
COPY api/go.sum .

# airの設定ファイルをコピー
COPY api/*air.toml .

RUN go mod download

COPY ./api .

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin


CMD ["air"]
